import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cms.zynkatech.com/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Himanshu@zynka.ai');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Himanshu@123');
  await page.locator('iframe[name="a-nsfo0cg0xxgs"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-nsfo0cg0xxgs"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-nsfo0cg0xxgs"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-nsfo0cg0xxgs"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-nsfo0cg0xxgs"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-nsfo0cg0xxgs"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-nsfo0cg0xxgs"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByText('Change').click();
  await page.getByRole('paragraph').filter({ hasText: 'trtest' }).click();
  await page.getByRole('link', { name: 'Icon Charge Points' }).click();
  await page.getByRole('button', { name: 'Add Charge Point' }).click();
  await page.getByRole('textbox', { name: 'Chargebox Id' }).click();
  await page.getByRole('textbox', { name: 'Chargebox Id' }).fill('khamariaChargerId');
  await page.getByRole('textbox', { name: 'Chargebox name' }).click();
  await page.getByRole('textbox', { name: 'Chargebox name' }).fill('Khamaria charger');
  await page.getByRole('combobox', { name: 'Registration Status *' }).click();
  await page.getByRole('option', { name: 'Accepted' }).click();
  await page.getByRole('combobox', { name: 'Charger Type * DC' }).click();
  await page.getByRole('option', { name: 'AC' }).click();
  await page.getByRole('checkbox', { name: 'Insert connector status after' }).check();
  await page.getByRole('textbox', { name: 'Name', exact: true }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('12');
  await page.getByRole('combobox', { name: 'Price Group' }).click();
  await page.getByRole('option', { name: 'new test price grp' }).click();
  await page.getByRole('combobox', { name: 'Connector Type' }).click();
  await page.getByRole('option', { name: 'CCS Type 2' }).click();
  await page.getByRole('spinbutton', { name: 'Kilo Watt' }).click();
  await page.getByRole('spinbutton', { name: 'Kilo Watt' }).fill('123');
  await page.getByRole('spinbutton', { name: 'Volt' }).click();
  await page.getByRole('spinbutton', { name: 'Volt' }).fill('249');
  await page.getByRole('button', { name: 'Add More Connectors' }).click();
  await page.getByRole('button', { name: 'Add More Connectors' }).click();
  await page.locator('#mui-83').click();
  await page.locator('#mui-83').fill('133');
  await page.getByRole('combobox', { name: 'Price Group new test price grp' }).nth(1).click();
  await page.getByRole('option', { name: 'new test price grp' }).click();
  await page.getByRole('combobox', { name: 'Connector Type CCS Type' }).nth(1).click();
  await page.getByRole('option', { name: 'CCS Type 2' }).click();
  await page.locator('#mui-86').click();
  await page.locator('#mui-86').fill('120');
  await page.locator('#mui-87').click();
  await page.locator('#mui-87').fill('250');
  await page.locator('#mui-88').click();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('decription for charger');
  await page.getByRole('checkbox', { name: 'Make Charger public' }).check();
  await page.goto('https://cms.zynkatech.com/dashboard');
  await page.getByRole('link', { name: 'Icon Resident RFID' }).click();
  await page.getByRole('button', { name: 'Add New RFID Tag' }).click();
  await page.getByRole('textbox', { name: 'Enter ID Tag' }).click();
  await page.getByRole('textbox', { name: 'Enter ID Tag' }).fill('kId');
  await page.getByText('Block all transactions').click();
  await page.getByRole('option', { name: 'Allow unlimited transactions' }).click();
  await page.getByText('Allow unlimited transactions').click();
  await page.getByRole('option', { name: 'Block all transactions' }).click();
  await page.getByRole('button', { name: 'Choose date' }).click();
  await page.getByRole('gridcell', { name: '17' }).click();
  await page.getByRole('textbox', { name: 'Enter any notes' }).click();
  await page.getByRole('textbox', { name: 'Enter any notes' }).fill('Notesfor rfid');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Icon Price Group' }).click();
  await page.getByRole('link', { name: 'Add Price Group' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('pricegroupForTrtest');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Name' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('pricegroupForTrtest description');
  await page.getByRole('spinbutton', { name: 'Price Per KWh' }).click();
  await page.getByRole('spinbutton', { name: 'Price Per KWh' }).fill('01200');
  await page.getByRole('spinbutton', { name: 'Fixed Fee Starting' }).click();
  await page.getByRole('spinbutton', { name: 'Fixed Fee Starting' }).fill('01');
  await page.getByRole('spinbutton', { name: 'Price Per KWh' }).click();
  await page.getByRole('spinbutton', { name: 'Fixed Fee Starting' }).fill('0');
  await page.getByRole('spinbutton', { name: 'Price Per KWh' }).fill('012');
  await page.getByRole('spinbutton', { name: 'Fixed Fee Charging' }).click();
  await page.getByRole('spinbutton', { name: 'Fixed Fee Charging' }).fill('05');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Add Price Group' }).click();
  await page.getByRole('spinbutton', { name: 'Fixed Fee Starting' }).click();
  await page.getByRole('spinbutton', { name: 'Fixed Fee Starting' }).fill('013');
  await page.getByRole('spinbutton', { name: 'Price Per KWh' }).click();
  await page.getByRole('spinbutton', { name: 'Price Per KWh' }).fill('0122');
  await page.getByRole('spinbutton', { name: 'Fixed Fee Charging' }).click();
  await page.getByRole('spinbutton', { name: 'Fixed Fee Charging' }).fill('06');
  await page.getByRole('spinbutton', { name: 'Fixed Fee Starting' }).click();
  await page.getByRole('spinbutton', { name: 'Price Per KWh' }).click();
  await page.getByRole('spinbutton', { name: 'Price Per KWh' }).fill('012');
  await page.getByRole('spinbutton', { name: 'Price Per KWh' }).press('F12');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('r');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('.MuiDataGrid-row.MuiDataGrid-row--lastVisible > div:nth-child(5) > .datatable__actions > .MuiButtonBase-root').click();
  await page.locator('.MuiBackdrop-root.MuiBackdrop-invisible').click();
  await expect(page.getByRole('cell', { name: 'r', exact: true })).toBeVisible();
  await page.locator('.MuiDataGrid-row.MuiDataGrid-row--lastVisible > div:nth-child(5) > .datatable__actions > .MuiButtonBase-root').click();
  await page.getByRole('menuitem', { name: 'Edit' }).click();
  await page.getByRole('link', { name: 'Cancel' }).click();
  await page.locator('.MuiDataGrid-row.MuiDataGrid-row--lastVisible > div:nth-child(5) > .datatable__actions > .MuiButtonBase-root').click();
  await page.getByText('Delete').click();
  await page.getByRole('link', { name: 'Icon Residents' }).click();
  await page.getByRole('link', { name: 'Add Resident' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('abhay@zynka.ai');
  await page.getByRole('textbox', { name: 'First Name' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'First Name' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('abhay@zynka.ai');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'First Name' }).fill('abhay');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('k');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('8052164990');
  await page.getByRole('tab', { name: 'ADDRESS' }).click();
  await page.getByRole('textbox', { name: 'Search Place' }).click();
  await page.getByRole('textbox', { name: 'Search Place' }).fill('aurai');
  await page.getByText('AuraiUttar Pradesh, India').click();
  await page.getByRole('tab', { name: 'RFID TAGS' }).click();
  await page.getByRole('combobox', { name: 'Avaliable Tags' }).click();
  await page.getByRole('option', { name: 'kId' }).click();
  await page.getByRole('button', { name: 'Attach Tags' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('tab', { name: 'GENERAL' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('8052164991');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('8052164992');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('body').press('ControlOrMeta+Shift+I');
});